### ISSUE TITLE
only 13 devices sent to my broker.

### ISSUE THREAD

**Issue by MattL0** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#15]
I only saw 13 different mac adress Is that normal?

The script works great for those ip.

thanks a lot

**Comment by MattL0** [comment]
haaa sorry... I get it. This is only for wifi device. 

Is there a possibility to expend this for all connected device?

**Comment by dersimn** [comment]
You could try to get your information about wired clients from the DHCP reservation list (same thing that is shown on the first 'Status' page of OpenWRT's LuCI). 

That would only cover clients that are actually using DHCP and you won't find out if a client is gone, because clients only contact the DHCP when they arrive, not when they leave.

**Comment by MattL0** [comment]
thanks !
