### ISSUE TITLE
rules syntax throws error in openhab log

### ISSUE THREAD

**Issue by ghost** [dersimn/OpwnWRT-Presence-Detector-over-MQTT#2]
I'm continuely getting an error in the openhab log.

`2017-07-23 18:43:30.021 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Wifi Detection: java.lang.Number`

Ive copied the rules from code and everything seems to be working apart from the rules.

any ideas?
P.S I'm really impressed with presence idea you've created its the reason I researched openwrt and bought a router that was compatible.

**Comment by dersimn** [comment]
[Line 6](https://github.com/dersimn/OpenWRT-Presence-Detector-over-MQTT/blob/6bd41ffab573acad4669f994a084ed8fbd4ccf2a/sample/OpenHAB/rules/wifi_detection.rules#L6) and similar lines in the example:  
This error frequently occurs when `Person_1_Wifi_LastSeen_Seconds` is not (yet) populated with a numeric value, for e.g. right after starting OpenHAB, when you haven't got a `LastSeen` value from the router yet. once your Router sent the first value the error should stop firing.

The error doesn't do any harm, that's why I didn't care about fixing these. Feel free to implement an `if ()` to prevent these error.

**Comment by ghost** [comment]
Thank you, as you say it sorted it self out  once it received an event update from the router.
